site_name: CoRA Docs
#site_url: http://www.mkdocs.org
site_description: CoRA documentation with Markdown.
site_author: Sachin Pawaskar

repo_url: https://github.com/spawaskar-cora/cora-docs-mkdocs
edit_uri: ""

pages:
    - Home: index.md
    - User Guide:
        - Projects: user-guide/projects.md
    - About:
        - Contributing: about/contributing.md

#extra_css:
#    - css/extra.css

#markdown_extensions:
#    - toc:
#        permalink: 
#    - admonition
#    - def_list

# copyright: Copyright &copy; 2016 - 2018 <a href="https://sachinpawaskaruno.github.io">Sachin Pawaskar</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">CoRA Team</a>.
# google_analytics: ['UA-27795084-5', 'mkdocs.org']

#plugins:
#    - search
